---
version: "3"
services:
  db1:
    build: .
    command: ./server --peer-on 0.0.0.0:9001 1
    ports:
      - "19001:9000"
      - "9001"
    networks:
      - peer
    volumes:
      - "data1:/data/"
    environment:
      - RUST_BACKTRACE=1
  db2:
    build: .
    command: ./server --peer-on 0.0.0.0:9002 2
    ports:
      - "19002:9000"
      - "9002"
    networks:
      - peer
    volumes:
      - "data2:/data/"
    environment:
      - RUST_BACKTRACE=1
  db3:
    build: .
    command: ./server --peer-on 0.0.0.0:9003 3
    networks:
      - peer
    ports:
      - "19003:9000"
      - "9003"
    volumes:
      - "data3:/data/"
    environment:
      - RUST_BACKTRACE=1

networks:
  peer:
    driver: bridge

volumes:
  data1:
  data2:
  data3:
