---
version: "3"
services:
  db1:
    build: .
    command: ./server --peer-on 0.0.0.0:9001 1 2-db2:9002 3-db3:9003
    ports:
      - "19001:9000"
      - "9001"
    networks:
      - peer
  db2:
    build: .
    command: ./server --peer-on 0.0.0.0:9002 2 1-db1:9001 3-db3:9003
    ports:
      - "19002:9000"
      - "9002"
    networks:
      - peer
  db3:
    build: .
    command: ./server --peer-on 0.0.0.0:9003 3 1-db1:9001 2-db2:9002
    networks:
      - peer
    ports:
      - "19003:9000"
      - "9003"

networks:
  peer:
    driver: bridge
